[esp32-s3-std-tutorial]
wifi_ssid = "Silent Rain"
wifi_psk = "pass"

[wifi_check]
wifi_ssid = "Silent Rain"
wifi_psk = "asdfghjkl123"

[http_client]
wifi_ssid = "Silent Rain"
wifi_psk = "asdfghjkl123"

[https_client]
wifi_ssid = "Silent Rain"
wifi_psk = "asdfghjkl123"
