[package]
name = "oled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp-idf-hal = "0.42.5"
embedded-hal = "0.2.7"
anyhow = "1.0.75"
