[build]
target = "xtensa-esp32s3-espidf"
# 加快编译速度 +nightly
rustflags = ["-Z", "threads=8"]

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "--cfg",
    "espidf_time64",
] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32s3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.1"
# 工具链路径设置为全局（global）
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
