version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nalgebra
    versions:
    - 0.24.0
    - 0.24.1
    - 0.25.0
    - 0.25.1
    - 0.25.3
    - 0.25.4
    - 0.26.1
  - dependency-name: linux-embedded-hal
    versions:
    - 0.3.0
